name: Deploy to GAE

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SA_KEY: ${{ secrets.ACCOUNT_KEY}}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: "Setup gcloud CLI"
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: $SA_KEY
        project_id: $PROJECT_ID
        export_default_credentials: true

    - name: "Create & Deploy"
    - run: |-
          gcloud services enable appengine.googleapis.com
          gcloud app create --region="us-central" || echo "App Already Present"
          gcloud app deploy --quiet --project=$PROJECT_ID
