name: Deploy to GAE

on:
  push:
    branches: [ master,sdk-working ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  
jobs:
  setup:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.ACCOUNT_KEY}}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true 
      # - name: Configure Docker
      #   run: |-
      #     gcloud services enable appengine.googleapis.com
          # gcloud --quiet auth configure-docker
      
      # # Build the Docker image
      # - name: Build Docker
      #   run: |-
      #     docker build -t "gcr.io/$PROJECT_ID/gcp-appengine" .
          
      # # Push the Docker image to Google Container Registry
      # - name: Publish Docker Image
      #   run: |-
      #     docker push "gcr.io/$PROJECT_ID/gcp-appengine"
    
      # Deploy to the GAE
      - name: Deploy to GAE
        run: |-
          cd src/
          gcloud app deploy --quiet --version=python --project=$PROJECT_ID 
      # - id: 'deploy' 
      #   name: Deploy to GAE
      #   run: |-
      #     gcloud services enable appengine.googleapis.com
      #     gcloud app create --region="us-central" || echo "App Already Present"
      #     gcloud app deploy --quiet --version=python --project=${{ secrets.PROJECT_ID }} 
        
    
